spring:
  mongodb:
    uri: mongodb://root:rYXXqz-VrewRXTSxe_1sYdwmNdC0eoMMXJcE0QgdBGPbz1Ed@4f53f7ae-1309-4296-b2bf-6f219675f983.asia-south1.firestore.goog:443/eca-customer?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false